import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContextWrapper from "./components/ContextWrapper";
import Header from "./components/Header";
import Nav from "./components/Nav";
import UserList from "./components/UserList";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Social-App",
  description: "Generated by Łukasz Surma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextWrapper>
          <div className="flex min-h-screen flex-col dark:bg-my-dark">
            <Header />
            <Nav />
            {children}
            <UserList />
          </div>
        </ContextWrapper>
      </body>
    </html>
  );
}
